global:
  resolve_timeout: 5m

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - send_resolved: true
        channel: '#alert'  # Replace with your Slack channel name
        api_url: 'https://hooks.slack.com/services/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'  # Replace with your actual Slack Webhook URL
        title: '🔥 [ALERT] {{ .CommonLabels.alertname }}'
        text: '🚨 *Instance:* {{ .CommonLabels.instance }}\n*Severity:* {{ .CommonLabels.severity }}\n*Description:* {{ .CommonAnnotations.description }}'
